version: "3.7"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "P1ssw@rd"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    command: /bin/bash /scripts/start-sql-server.sh
    volumes:
      - ./install/:/scripts/
